### ISSUE TITLE
Steve will drop into the sitting block after stand up

### ISSUE THREAD

**Issue by CwavGuy** [geilmaker/SitDown#1]
Great Plugin!!! I am so appreciative of its simplicity and usefulness. But Steve will drop into the sitting block after stand up and I have to jump out from my seat. If there is a hole under my sitting block, Steve will be trapped inside.

![image](https://user-images.githubusercontent.com/25190647/132137975-7257b5cb-52cf-4c70-99f0-d41b3c3f9195.png)

**Comment by da-wilky** [comment]
Hey :)
Nice to hear, thx man, was just a little fun project, as soon as I got some time to spend I'll have a look :)
May I ask at first which Version you are running?
Have a nice one :)

**Comment by da-wilky** [comment]
I think I was able to fix the issue in the new release for minecraft version 1.17.1. Hope it works fine on ur system too. If you have any questions or problems left just ask :)
